/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simba;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Insert extends javax.swing.JFrame {
    Database database;
    
//    static String nama,sd,ss,tgl,g;
//    static int ad,as,id;
    /**
     * Creates new form Insert
     */
    public Insert() {
        initComponents();
        setLocationRelativeTo(null);
//        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
//        Date date = new Date();
//        tfkondisi.setText(dateFormat.format(date));
//        tfkondisi.disable();
        database = new Database();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lsubmit = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        tfjumlah = new javax.swing.JTextField();
        tfnilai = new javax.swing.JTextField();
        tfkondisi = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Nama");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 60, 35, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Jumlah");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 100, 46, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nilai");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 140, 28, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Kondisi");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 190, 46, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Insert");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(330, 20, 51, 15);

        lsubmit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lsubmit.setText("Submit");
        lsubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lsubmitMouseClicked(evt);
            }
        });
        jPanel1.add(lsubmit);
        lsubmit.setBounds(299, 265, 70, 20);

        tfnama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tfnama);
        tfnama.setBounds(130, 60, 250, 20);

        tfjumlah.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tfjumlah);
        tfjumlah.setBounds(130, 100, 250, 20);

        tfnilai.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tfnilai);
        tfnilai.setBounds(130, 140, 250, 20);

        tfkondisi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tfkondisi);
        tfkondisi.setBounds(130, 190, 250, 20);
        jPanel1.add(background);
        background.setBounds(0, 0, 400, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lsubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsubmitMouseClicked
        // TODO add your handling code here:
        try {
            
            String sql = "INSERT INTO aset VALUES (?,?,?,?,?)";
            PreparedStatement pst;
            pst = database.conn.prepareStatement(sql);
            
            pst.setNull(1, java.sql.Types.INTEGER);
            pst.setString(2, tfnama.getText());
            pst.setInt(3, Integer.parseInt(tfjumlah.getText()));
            pst.setInt(4, Integer.parseInt(tfnilai.getText()));
            pst.setString(5, tfkondisi.getText());
            
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Input Berhasil");
            
            Aset aset = new Aset();
            aset.setVisible(true);
            aset.setLocationRelativeTo(null);
//            nama=tfnama.getText();
//            sd=cbsuratd.getModel().getSelectedItem().toString();
//            ss=cbsurats.getModel().getSelectedItem().toString();
//            ad=Integer.parseInt(tfayatd.getText());
//            as=Integer.parseInt(tfayats.getText());
//            tgl=tftgl.getText();
//            g=rbguru;
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
        }
    }//GEN-LAST:event_lsubmitMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lsubmit;
    private javax.swing.JTextField tfjumlah;
    private javax.swing.JTextField tfkondisi;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfnilai;
    // End of variables declaration//GEN-END:variables
}
