/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simba;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javazoom.jl.decoder.JavaLayerException;
import javazoom.jl.player.Player;


public class Login extends javax.swing.JFrame {
    public static Login login;
    public Database database;
    public Home home;
    public Player ply;
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
        database = new Database();
        setLocationRelativeTo(null);
    }
    public void loginAdmin(){
        
        PreparedStatement ps;
        try {
            ps = database.conn.prepareStatement("select * from user");
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                if(rs.getString(2).equals(tfusername.getText())&&rs.getString(3).equals(pfpassword.getText())){
                    JOptionPane.showMessageDialog(null, "Selamat Datang Admin");
                    home = new Home();
                    home.setVisible(true);
                    home.setLocationRelativeTo(null);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "Input Salah");
                }
            }
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Belum Terkoneksi Database");
        }    
    }
    private static void soundClick() throws JavaLayerException{
        try{
            String path=null;
            path = System.getProperty("user.dir")+"/src/simba/click.mp3";
            FileInputStream fis = new FileInputStream(path);
            
            Player ply = new Player(fis);
            ply.play();
            new Thread(){
                @Override
                public void run() {
                    try {
                        ply.play();//To change body of generated methods, choose Tools | Templates.
                    } catch (JavaLayerException ex) {
                    }
                } 
            }.start();
        }catch(FileNotFoundException e){
            
        }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lsubmit = new javax.swing.JLabel();
        pfpassword = new javax.swing.JPasswordField();
        lusername = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        lpassword = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        backgrond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vamos Futsal");

        jPanel1.setLayout(null);

        lsubmit.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        lsubmit.setText("Sign In");
        lsubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lsubmitMouseClicked(evt);
            }
        });
        jPanel1.add(lsubmit);
        lsubmit.setBounds(180, 220, 80, 30);
        jPanel1.add(pfpassword);
        pfpassword.setBounds(40, 180, 220, 20);

        lusername.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        lusername.setText("Username");
        jPanel1.add(lusername);
        lusername.setBounds(40, 80, 90, 19);

        tfusername.setFont(new java.awt.Font("Century Schoolbook L", 0, 12)); // NOI18N
        jPanel1.add(tfusername);
        tfusername.setBounds(40, 110, 220, 22);

        lpassword.setFont(new java.awt.Font("Century Schoolbook L", 1, 14)); // NOI18N
        lpassword.setText("Password");
        jPanel1.add(lpassword);
        lpassword.setBounds(40, 150, 90, 19);

        judul.setFont(new java.awt.Font("Century Schoolbook L", 1, 18)); // NOI18N
        judul.setText("SIMBA");
        jPanel1.add(judul);
        judul.setBounds(110, 20, 70, 24);
        jPanel1.add(logo);
        logo.setBounds(180, 20, 50, 60);
        jPanel1.add(backgrond);
        backgrond.setBounds(0, 0, 400, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lsubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsubmitMouseClicked
        // TODO add your handling code here:
        loginAdmin();
    }//GEN-LAST:event_lsubmitMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgrond;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel lpassword;
    private javax.swing.JLabel lsubmit;
    private javax.swing.JLabel lusername;
    private javax.swing.JPasswordField pfpassword;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
