/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simba;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Update extends javax.swing.JFrame {
    Database database;
    Aset u;
    
    /**
     * Creates new form Insert
     */
    public Update() {
        initComponents();
        u = new Aset();
        setLocationRelativeTo(null);
        tfnama.setText(u.nama);
        tfjumlah.setText(Integer.toString(u.jml));
        tfnilai.setText(Integer.toString(u.ni));
        tfkondisi.setText(u.kon);
//        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
//        Date date = new Date();
//        tftgl.setText(dateFormat.format(date));
//        tftgl.disable();
//        database = new Database();
//        tfnama.setText(u.nama);
//        tfayatd.setText(Integer.toString(u.ad));
//        tfayats.setText(Integer.toString(u.as));
//        rbguru1.setText(u.g);
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lsubmit = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        tfjumlah = new javax.swing.JTextField();
        tfnilai = new javax.swing.JTextField();
        tfkondisi = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Nama");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 60, 35, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Jumlah");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 100, 50, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Nilai");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 140, 28, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Kondisi");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 190, 46, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Update");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(320, 20, 60, 20);

        lsubmit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lsubmit.setText("Submit");
        lsubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lsubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lsubmitMouseClicked(evt);
            }
        });
        jPanel1.add(lsubmit);
        lsubmit.setBounds(299, 265, 70, 20);

        back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back.setText("Kembali");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(30, 270, 60, 23);

        tfnama.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tfnama);
        tfnama.setBounds(130, 60, 250, 20);

        tfjumlah.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tfjumlah);
        tfjumlah.setBounds(130, 100, 250, 20);

        tfnilai.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tfnilai);
        tfnilai.setBounds(130, 140, 250, 20);

        tfkondisi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(tfkondisi);
        tfkondisi.setBounds(130, 190, 250, 20);
        jPanel1.add(background);
        background.setBounds(0, 0, 400, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lsubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lsubmitMouseClicked
        // TODO add your handling code here:
        try {
            System.err.println(u.id);
            String sql = "UPDATE aset SET nama='"+tfnama.getText()+"',jumlah='"+Integer.parseInt(tfjumlah.getText())+"',nilai='"+Integer.parseInt(tfnilai.getText())+"',kondisi='"+tfkondisi.getText()+"' WHERE id_aset='"+u.id+"'";
            PreparedStatement pst;
            pst = database.conn.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Update Berhasil");
            this.dispose();
            new Aset().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan here");
        }
    }//GEN-LAST:event_lsubmitMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new Aset().setVisible(true);
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lsubmit;
    private javax.swing.JTextField tfjumlah;
    private javax.swing.JTextField tfkondisi;
    private javax.swing.JTextField tfnama;
    private javax.swing.JTextField tfnilai;
    // End of variables declaration//GEN-END:variables
}
